# Generated by Django 5.2.1 on 2025-06-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_facultyprofile_faculty_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admn_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
